class: com.guidewire.upgrade.steps.granite.pl.InboundIntegrationConfigUpgradeStep
description: Convert inbound-integration-config.xml to the format compatible with release 10.0.x.
targetVersion: 10.0.0